export const clothsArr = [
  {
    id: 1,
    image: require("../img/blue_t.png"),
    gendeAndSize: "male, larzy size",
    type: "t",
    color: "blue",
  },
  {
    id: 2,
    image: require("../img/blue_p.png"),
    gendeAndSize: "male, small size",
    type: "p",
    color: "blue",
  },
  {
    id: 3,
    image: require("../img/blue_s.png"),
    gendeAndSize: "female, larzy size",
    type: "s",
    color: "blue",
  },
  {
    id: 4,
    image: require("../img/yellow_t.png"),
    gendeAndSize: "female larzy size",
    type: "t",
    color: "yellow",
  },
  {
    id: 5,
    image: require("../img/yellow_p.png"),
    gendeAndSize: "male, larzy size",
    type: "p",
    color: "yellow",
  },
  {
    id: 6,
    image: require("../img/yellow_s.png"),
    gendeAndSize: "male, larzy size",
    type: "s",
    color: "yellow",
  },
  {
    id: 7,
    image: require("../img/pink_t.png"),
    gendeAndSize: "female, larzy size",
    type: "t",
    color: "pink",
  },
  {
    id: 8,
    image: require("../img/pink_p.png"),
    gendeAndSize: "female, small size",
    type: "p",
    color: "pink",
  },
  {
    id: 9,
    image: require("../img/pink_s.png"),
    gendeAndSize: "female,larzy size",
    type: "s",
    color: "pink",
  },

  {
    id: 10,
    image: require("../img/blue_t.png"),
    gendeAndSize: "male, larzy size",
    type: "t",
    color: "blue",
  },
  {
    id: 11,
    image: require("../img/blue_p.png"),
    gendeAndSize: "male, small size",
    type: "p",
    color: "blue",
  },
  {
    id: 12,
    image: require("../img/blue_s.png"),
    gendeAndSize: "female, larzy size",
    type: "s",
    color: "blue",
  },
  {
    id: 13,
    image: require("../img/yellow_t.png"),
    gendeAndSize: "female larzy size",
    type: "t",
    color: "yellow",
  },
  {
    id: 14,
    image: require("../img/yellow_p.png"),
    gendeAndSize: "male, larzy size",
    type: "p",
    color: "yellow",
  },
  {
    id: 15,
    image: require("../img/yellow_s.png"),
    gendeAndSize: "male, larzy size",
    type: "s",
    color: "yellow",
  },
  {
    id: 16,
    image: require("../img/pink_t.png"),
    gendeAndSize: "female, small size",
    type: "t",
    color: "pink",
  },
  {
    id: 17,
    image: require("../img/pink_p.png"),
    gendeAndSize: "female, small size",
    type: "p",
    color: "pink",
  },
  {
    id: 18,
    image: require("../img/pink_s.png"),
    gendeAndSize: "female,larzy size",
    type: "s",
    color: "pink",
  },
];
